const currencyList = [
  { name: "Afghan Afghani", symbol: "؋", rounding: true },
  { name: "Albanian Lek", symbol: "L", rounding: true },
  { name: "Armenian Dram", symbol: "֏", rounding: true },
  { name: "Angolan Kwanza", symbol: "Kz", rounding: true },
  { name: "Argentine Peso", symbol: "$", rounding: true },
  { name: "Australian Dollar", symbol: "$", rounding: false },
  { name: "Aruban Florin", symbol: "ƒ", rounding: false },
  { name: "Azerbaijani Manat", symbol: "₼", rounding: true },
  { name: "Algerian Dinar", symbol: "د.ج", rounding: true },
  { name: "Bosnia-Herzegovina Convertible Mark", symbol: "KM", rounding: false },
  { name: "Barbadian Dollar", symbol: "$", rounding: false },
  { name: "Bangladeshi Taka", symbol: "৳", rounding: true },
  { name: "Bulgarian Lev", symbol: "лв", rounding: false },
  { name: "Bahraini Dinar", symbol: ".د.ب", rounding: false },
  { name: "Burundian Franc", symbol: "FBu", rounding: true },
  { name: "Bermudan Dollar", symbol: "$", rounding: false },
  { name: "Brunei Dollar", symbol: "$", rounding: false },
  { name: "Bolivian Boliviano", symbol: "Bs.", rounding: true },
  { name: "Brazilian Real", symbol: "R$", rounding: false },
  { name: "Bahamian Dollar", symbol: "$", rounding: false },
  { name: "Bitcoin", symbol: "₿", rounding: false },
  { name: "Bhutanese Ngultrum", symbol: "Nu.", rounding: true },
  { name: "Botswanan Pula", symbol: "P", rounding: true },
  { name: "Belarusian Ruble", symbol: "Br", rounding: true },
  { name: "Belize Dollar", symbol: "$", rounding: false },
  { name: "British Pound Sterling", symbol: "£", rounding: false },
  { name: "Canadian Dollar", symbol: "$", rounding: false },
  { name: "Congolese Franc", symbol: "FC", rounding: true },
  { name: "Chilean Peso", symbol: "$", rounding: true },
  { name: "Chinese Yuan", symbol: "¥", rounding: false },
  { name: "Colombian Peso", symbol: "$", rounding: true },
  { name: "Costa Rican Colón", symbol: "₡", rounding: true },
  { name: "Cuban Convertible Peso", symbol: "$", rounding: false },
  { name: "Cuban Peso", symbol: "₱", rounding: true },
  { name: "Cape Verdean Escudo", symbol: "$", rounding: true },
  { name: "Czech Republic Koruna", symbol: "Kč", rounding: false },
  { name: "Croatian Kuna", symbol: "kn", rounding: false },
  { name: "Cambodian Riel", symbol: "៛", rounding: true },
  { name: "Comorian Franc", symbol: "CF", rounding: true },
  { name: "Cayman Islands Dollar", symbol: "$", rounding: false },
  { name: "CFA Franc BEAC", symbol: "FCFA", rounding: true },
  { name: "CFA Franc BCEAO", symbol: "CFA", rounding: true },
  { name: "CFP Franc", symbol: "F", rounding: true },
  { name: "Djiboutian Franc", symbol: "Fdj", rounding: true },
  { name: "Danish Krone", symbol: "kr", rounding: false },
  { name: "Dominican Peso", symbol: "$", rounding: true },
  { name: "Egyptian Pound", symbol: "£", rounding: true },
  { name: "Eritrean Nakfa", symbol: "Nfk", rounding: true },
  { name: "Ethiopian Birr", symbol: "Br", rounding: true },
  { name: "Euro", symbol: "€", rounding: false },
  { name: "East Caribbean Dollar", symbol: "$", rounding: false },
  { name: "Fijian Dollar", symbol: "$", rounding: false },
  { name: "Falkland Islands Pound", symbol: "£", rounding: false },
  { name: "Georgian Lari", symbol: "₾", rounding: true },
  { name: "Guernsey Pound", symbol: "£", rounding: false },
  { name: "Ghanaian Cedi", symbol: "₵", rounding: true },
  { name: "Gibraltar Pound", symbol: "£", rounding: false },
  { name: "Gambian Dalasi", symbol: "D", rounding: true },
  { name: "Guinean Franc", symbol: "FG", rounding: true },
  { name: "Guatemalan Quetzal", symbol: "Q", rounding: true },
  { name: "Guyanaese Dollar", symbol: "$", rounding: false },
  { name: "Gold (troy ounce)", symbol: "Au", rounding: false },
  { name: "Hong Kong Dollar", symbol: "$", rounding: false },
  { name: "Honduran Lempira", symbol: "L", rounding: true },
  { name: "Haitian Gourde", symbol: "G", rounding: true },
  { name: "Hungarian Forint", symbol: "Ft", rounding: true },
  { name: "Indonesian Rupiah", symbol: "Rp", rounding: true },
  { name: "Israeli New Sheqel", symbol: "₪", rounding: false },
  { name: "Indian Rupee", symbol: "₹", rounding: true },
  { name: "Iraqi Dinar", symbol: "د.ع", rounding: true },
  { name: "Iranian Rial", symbol: "﷼", rounding: true },
  { name: "Icelandic Króna", symbol: "kr", rounding: false },
  { name: "Japanese Yen", symbol: "¥", rounding: true },
  { name: "Kenyan Shilling", symbol: "KSh", rounding: true },
  { name: "Kuwaiti Dinar", symbol: "KD", rounding: false },
  { name: "Mexican Peso", symbol: "$", rounding: true },
  { name: "Nigerian Naira", symbol: "₦", rounding: true },
  { name: "Norwegian Krone", symbol: "kr", rounding: false },
  { name: "Omani Rial", symbol: "﷼", rounding: false },
  { name: "Pakistani Rupee", symbol: "₨", rounding: true },
  { name: "Philippine Peso", symbol: "₱", rounding: true },
  { name: "United States Dollar", symbol: "$", rounding: false },
  { name: "Venezuelan Bolívar Fuerte", symbol: "Bs", rounding: true },
  { name: "Vietnamese Dong", symbol: "₫", rounding: true },
  { name: "Zambian Kwacha", symbol: "ZK", rounding: true },
  { name: "Swiss Franc", symbol: "CHF", rounding: true },
  { name: "Swedish Krona", symbol: "kr", rounding: false },
  { name: "Malaysian Ringgit", symbol: "RM", rounding: true },
  { name: "Singapore Dollar", symbol: "S$", rounding: false },
  { name: "New Zealand Dollar", symbol: "$", rounding: false },
  { name: "South Korean Won", symbol: "₩", rounding: false },
  { name: "Ukrainian Hryvnia", symbol: "₴", rounding: true },
  { name: "Mauritian Rupee", symbol: "₨", rounding: true },
  { name: "Nepalese Rupee", symbol: "₨", rounding: true },
  { name: "Sri Lankan Rupee", symbol: "රු", rounding: true },
  { name: "Mongolian Tögrög", symbol: "₮", rounding: true },
  { name: "Malawian Kwacha", symbol: "MK", rounding: true },
  { name: "Moldovan Leu", symbol: "L", rounding: true },
  { name: "Macedonian Denar", symbol: "ден", rounding: true },
  { name: "Mauritanian Ouguiya", symbol: "UM", rounding: true },
  { name: "Maldivian Rufiyaa", symbol: "Rf", rounding: true },
  { name: "Moroccan Dirham", symbol: "د.م.", rounding: true },
  { name: "Myanmar Kyat", symbol: "K", rounding: true },
  { name: "Namibian Dollar", symbol: "$", rounding: false },
  { name: "Nicaraguan Córdoba", symbol: "C$", rounding: true },
  { name: "Nepalese Rupee", symbol: "₨", rounding: true },
  { name: "Panamanian Balboa", symbol: "B/.", rounding: false },
  { name: "Papua New Guinean Kina", symbol: "K", rounding: true },
  { name: "Paraguayan Guarani", symbol: "₲", rounding: true },
  { name: "Peruvian Sol", symbol: "S/", rounding: false },
  { name: "Polish Złoty", symbol: "zł", rounding: false },
  { name: "Qatari Riyal", symbol: "ر.ق", rounding: false },
  { name: "Romanian Leu", symbol: "lei", rounding: false },
  { name: "Russian Ruble", symbol: "₽", rounding: true },
  { name: "Rwandan Franc", symbol: "FRw", rounding: true },
  { name: "Samoan Tala", symbol: "T", rounding: true },
  { name: "São Tomé and Príncipe Dobra", symbol: "Db", rounding: true },
  { name: "Saudi Riyal", symbol: "ر.س", rounding: false },
  { name: "Serbian Dinar", symbol: "дин", rounding: true },
  { name: "Seychellois Rupee", symbol: "₨", rounding: true },
  { name: "Sierra Leonean Leone", symbol: "Le", rounding: true },
  { name: "Solomon Islands Dollar", symbol: "$", rounding: true },
  { name: "Somali Shilling", symbol: "Sh", rounding: true },
  { name: "South African Rand", symbol: "R", rounding: false },
  { name: "South Sudanese Pound", symbol: "£", rounding: true },
  { name: "Sudanese Pound", symbol: "ج.س.", rounding: true },
  { name: "Surinamese Dollar", symbol: "$", rounding: true },
  { name: "Swazi Lilangeni", symbol: "L", rounding: false },
  { name: "Syrian Pound", symbol: "£", rounding: true },
  { name: "Tajikistani Somoni", symbol: "ЅМ", rounding: true },
  { name: "Tanzanian Shilling", symbol: "Sh", rounding: true },
  { name: "Thai Baht", symbol: "฿", rounding: false },
  { name: "Tongan Paʻanga", symbol: "T$", rounding: true },
  { name: "Trinidad and Tobago Dollar", symbol: "$", rounding: false },
  { name: "Tunisian Dinar", symbol: "د.ت", rounding: true },
  { name: "Turkish Lira", symbol: "₺", rounding: true },
  { name: "Turkmenistani Manat", symbol: "m", rounding: true },
  { name: "Ugandan Shilling", symbol: "USh", rounding: true },
  { name: "UAE Dirham", symbol: "د.إ", rounding: false },
  { name: "Uruguayan Peso", symbol: "$", rounding: true },
  { name: "Uzbekistani Som", symbol: "so'm", rounding: true },
  { name: "Vanuatu Vatu", symbol: "VT", rounding: true },
  { name: "Yemeni Rial", symbol: "﷼", rounding: true },
  { name: "Zimbabwean Dollar", symbol: "$", rounding: true },
];

export default currencyList;